word_list = [
    "PUMPKIN", "FRUIT", "SCHOOL", "APPLE", "BANANA", "GRAPE", "ORANGE", "STRAWBERRY", "RASPBERRY", "BLUEBERRY",
    "PYTHON", "JAVA", "JAVASCRIPT", "RUBY", "SWIFT", "KOTLIN", "GO", "RUST", "TYPESCRIPT", "CSHARP", "GITHUB",
    "LONDON", "PARIS", "BERLIN", "MADRID", "ROME", "DUBLIN", "LISBON", "VIENNA", "PRAGUE", "BUDAPEST",
    "ENGLAND", "FRANCE", "GERMANY", "SPAIN", "ITALY", "IRELAND", "PORTUGAL", "AUSTRIA", "SWITZERLAND", "HUNGARY",
    "ELEPHANT", "LION", "TIGER", "BEAR", "GIRAFFE", "ZEBRA", "KANGAROO", "PANDA", "KOALA", "MONKEY",
    "BASKETBALL", "FOOTBALL", "BASEBALL", "SOCCER", "TENNIS", "GOLF", "HOCKEY", "VOLLEYBALL", "RUGBY", "CRICKET",
    "PIANO", "GUITAR", "DRUMS", "VIOLIN", "FLUTE", "SAXOPHONE", "TRUMPET", "HARP", "CELLO", "UKULELE",
    "MATHEMATICS", "PHYSICS", "CHEMISTRY", "BIOLOGY", "ASTRONOMY", "GEOLOGY", "ECOLOGY", "ZOOLOGY", "BOTANY",
    "GENETICS",
    "DEMOCRACY", "MONARCHY", "REPUBLIC", "DICTATORSHIP", "FEDERATION", "CONFEDERATION", "EMPIRE", "KINGDOM",
    "PRINCIPALITY", "WEALTH", "DESTINY",
    "ZERO", "ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN"
]